export const testIds = {
  landing: {
    hero: "landing-hero",
    heroContent: "landing-hero-content",
    eyebrow: "landing-eyebrow",
    title: "landing-title",
    actions: "landing-actions",
    loginLink: "landing-login-link",
    registerLink: "landing-register-link",
    featureCard: "landing-feature-card",
    featureTitle: "landing-feature-title",
    featureMeta: "landing-feature-meta",
    metaSecurity: "landing-meta-security",
    metaSpeed: "landing-meta-speed",
    metaData: "landing-meta-data",
  },
  login: {
    page: "login-page",
    card: "login-card",
    title: "login-title",
    form: "login-form",
    emailInput: "login-email-input",
    passwordInput: "login-password-input",
    submitButton: "login-submit-button",
    meta: "login-meta",
    registerLink: "login-register-link",
    forgotButton: "login-forgot-button",
    toast: "login-toast",
  },
  register: {
    page: "register-page",
    card: "register-card",
    title: "register-title",
    form: "register-form",
    fullnameInput: "register-fullname-input",
    emailInput: "register-email-input",
    passwordInput: "register-password-input",
    submitButton: "register-submit-button",
    backLink: "register-back-link",
    toast: "register-toast",
  },
  dashboard: {
    page: "dashboard-page",
    header: "dashboard-header",
    eyebrow: "dashboard-eyebrow",
    greeting: "dashboard-greeting",
    roleBadge: "dashboard-role-badge",
    status: "dashboard-status",
    cards: "dashboard-cards",
    cardUsers: "dashboard-card-users",
    usersCount: "dashboard-users-count",
    cardActivity: "dashboard-card-activity",
    viewUsersLink: "dashboard-view-users-link",
    cardProfile: "dashboard-card-profile",
    updateProfileLink: "dashboard-update-profile-link",
    toast: "dashboard-toast",
  },
  users: {
    page: "users-page",
    header: "users-header",
    eyebrow: "users-eyebrow",
    title: "users-title",
    searchInput: "users-search-input",
    table: "users-table",
    rowHeader: "users-row-header",
    toast: "users-toast",
  },
  editUser: {
    page: "edit-user-page",
    card: "edit-user-card",
    title: "edit-user-title",
    form: "edit-user-form",
    fullnameInput: "edit-user-fullname-input",
    emailInput: "edit-user-email-input",
    actions: "edit-user-actions",
    saveButton: "edit-user-save-button",
    backLink: "edit-user-back-link",
    toast: "edit-user-toast",
  },
  profile: {
    page: "profile-page",
    card: "profile-card",
    title: "profile-title",
    form: "profile-form",
    fullnameInput: "profile-fullname-input",
    emailInput: "profile-email-input",
    passwordInput: "profile-password-input",
    roleSelect: "profile-role-select",
    actions: "profile-actions",
    saveButton: "profile-save-button",
    deleteButton: "profile-delete-button",
    toast: "profile-toast",
  },
  logout: {
    page: "logout-page",
    card: "logout-card",
    title: "logout-title",
    actions: "logout-actions",
    loginLink: "logout-login-link",
    homeLink: "logout-home-link",
  },
} as const;

export const testIdBuilders = {
  usersRow: (userId: number) => `users-row-${userId}`,
  usersRowId: (userId: number) => `users-row-${userId}-id`,
  usersRowName: (userId: number) => `users-row-${userId}-name`,
  usersRowEmail: (userId: number) => `users-row-${userId}-email`,
  usersRowActions: (userId: number) => `users-row-${userId}-actions`,
  usersEditLink: (userId: number) => `users-edit-link-${userId}`,
  usersDeleteButton: (userId: number) => `users-delete-button-${userId}`,
} as const;
